services:
  datascience:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./src:/workspace/src
      - ./tests:/workspace/tests
      - ./pyproject.toml:/workspace/pyproject.toml
      - ./poetry.lock:/workspace/poetry.lock
      - ./README.md:/workspace/README.md
    environment:
      - HOME=/tmp
    env_file:
      - path: .env
        required: false
